#%RAML 1.0 NamedExample
type: object
example: |
  {
    "status": "success",
    "data": {
    "user_id": "12345",
    "full_name": [
                   "e",
                   "o",
                   "D",
                   "<space>",
                   "n",
                   "h",
                   "o",
                   "J"
                 ],
      "contact_email": "john.doe@example.com"
            }
    }